import "Monitor.idl";

namespace PingMe
{
    [default_interface]
    runtimeclass AddMonitorDialog : Windows.UI.Xaml.Controls.Page
    {
        AddMonitorDialog();

        Monitor Add();
        void Edit(Monitor monitor);
    }
}
