namespace PingMe
{
    [bindable]
    [default_interface]
    runtimeclass Files 
    {
        Files();

        Windows.Foundation.IAsyncAction ReadMonitors();
        Windows.Foundation.IAsyncAction SaveMonitors();
    }
}
