import "CheckEvent.idl";
import "CheckEventControl.idl";
import "MonitorPreviewControl.idl";

namespace PingMe
{
    [bindable]
    [default_interface]
    runtimeclass Monitor 
    {
        Monitor();
        Monitor(String name, String host, String method, String body, String headers, String cookies, Int32 timeout);
        Monitor(String name, String host, String method, String body, String headers, String cookies, Int32 timeout, Boolean launch, Windows.Foundation.Collections.IVector<CheckEvent> events);
        
        MonitorPreviewControl Parent{ get; set; };

        void Check();
         
        void Continue();
        void Pause();

        Boolean IsLaunching();

        void LogHandler(Windows.Foundation.EventHandler<CheckEventControl> handler);
        Windows.Foundation.EventHandler<CheckEventControl> LogHandler();

        String Name{ get; };
        String Host{ get; };
        String Method{ get; };
        String Body{ get; };
        String Headers{ get; };
        String Cookies{ get; };
        Int32 Timeout{ get; };

        Windows.Foundation.Collections.IVector<CheckEvent> Events{ get; set; };
    }
}
