import "CheckEvent.idl";
import "MonitorPreviewControl.idl";

namespace PingMe
{
    [bindable]
    [default_interface]
    runtimeclass Monitor 
    {
        Monitor();
        Monitor(String name, String host, Int32 timeout);
        
        MonitorPreviewControl Parent{ get; set; };

        void Check();
         
        void Continue();
        void Pause();

        String Name{ get; };
        String Host{ get; };
        Int32 Timeout{ get; };

        Windows.Foundation.Collections.IVector<CheckEvent> Events{ get; };
    }
}
