import "Monitor.idl";
import "CheckEvent.idl";

namespace PingMe
{
    [default_interface]
    runtimeclass Pinger
    {
        Pinger();
        Pinger(Monitor monitor, Windows.Foundation.EventHandler<CheckEvent> handler);

        void Pause();
        void Continue();

        void Check();
    }
}
