namespace PingMe
{
    runtimeclass StatusControl : Windows.UI.Xaml.Controls.Control
    {
        StatusControl();
        static Windows.UI.Xaml.DependencyProperty ColorProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty MonitorNameProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty HostProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty CooldownProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty PointsProperty{ get; };

        Windows.UI.Xaml.Media.SolidColorBrush Color;
        String MonitorName;
        String Host;
        String Cooldown;
        String Points;

        void Update();
    }
}